spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: security
    url: jdbc:mysql://localhost:3306/security?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: gudrhs11

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#    show-sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 440169512538-lak0g41ncp34oqs49f97jvbladcb0e07.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 2912289775744469
            client-secret: fa1b09c4f46e7d7b1c4d12f829b623c8
            scope:
              - email
              - public_profile

          naver:
            client-id: kX9Kqzsxy1ZByzTHLLrU
            client-secret: 5sYA6qPbdy
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace



